import '@/app/globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { Gamepad2 } from 'lucide-react'
import AuthButtons from '@/components/auth/auth-buttons'
import { SessionProvider } from 'next-auth/react'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Authjs 5: Middleware',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {


  return (
    <html lang="es">
      <SessionProvider> 
    <body className={`bg-slate-100 ${inter.className} min-h-screen flex flex-col`}>
      
      <header className="h-14 bg-[var(--aside-card-background)] text-white flex px-10 py-2 justify-between items-center sticky top-0 z-50">
      <div className=" hidden md:flex flex-row items-center">
              <Gamepad2 className="w-12 h-12 mr-3" />
              <Link href="/" className="text-4xl font-bold">GAMES FOR US</Link>
            </div>
            <AuthButtons />
      </header>
  
      <div className="flex-1 flex">
        <main className="flex items-center justify-center w-full overflow-y-auto">
          {children}
          <Link
            href="/howtouse"
            className="fixed sm:bottom-15 sm:right-3 bottom-25 right-3 bg-blue-500 text-white px-6 py-3 rounded-full shadow-lg text-lg hover:bg-blue-600 transition"
          >
            ?
          </Link>
        </main>
      </div>
  
    </body>
    </SessionProvider>
  </html>
  
  )
}
